### ISSUE TITLE
Demo page and/or docs outdated

### ISSUE THREAD

**Issue by joechilds** [agoragames/confirm-with-reveal#12]
The demo page ( http://blog.agoragames.com/confirm-with-reveal/ ) shows that you can get a reveal-modal with just `data-confirm` on your link (ie. `<a href='/foo' data-confirm>`). In the current version, you can't do this, you need to specify `<a href='/foo' data-confirm='{}'>`.

It looks like it's caused by line 47:

      # The confirmation is actually triggered again when hitting "OK"
      # (or whatever) in the modal (since we clone the original link in),
      # but since we strip off the 'confirm' data attribute, we can tell
      # whether this is the first confirmation or a subsequent one.
      return true if !el_options

The demo page has the JS code of this instead:

    if (el_options == null) {
      el_options = {};
    }

Either the docs need updating on how you get a no-frills, basic reveal modal or the coffee needs changing to revert to `el_options = {}`. Or something :+1:

**Comment by jletourneau** [comment]
OK, very sorry this fell by the wayside for so long.

That commit to `master` just now should resolve this: I updated the library to properly handle a `data-confirm` attribute with no value (i.e. show the Foundation dialog).
